dist: trusty
script: "/bin/true"
notifications:
  email: false
  slack:
    rooms:
      secure: ILUBxYEoSUv2r6AUMw9JSGpW3eOu3gohrVKq/6klDhsvrOb7oFkYKICF869bKfcWck01Uxz3ytVCrYiqn/atmIublsDKO2gBtkPnnnOyf6EYMVbCdcHJOri3aDtYEhy4c4B2hjNiGjdjz+J6Ream8m2/xs+RnB9zS/CMRbE3Mpwn3ubpxwsh2RvwObLFaRsOvCa96NiJAK+nTolyJGirfoZZor8ukZ+Bd5rGF3wT6SSj0uRlUJfOxC6hMuHSD51cJ+OkSXoWK3lHCv++YLPrTIhWGIcaxezFQU0i5bxnu1Lq6kDDHOQoy6KOq1SJL+lI4h1a8lq4DwUWTuTbBzH6MvU4P7+Cj1WcHHb7xJ+vyzO4GSpYPv2dJQsz6lUQA3SlSmyyy1XF+O9dFplPO/BZfxOc/7TFj7Sakw8sGZ7iiLx7//Sw09clcEzw9g0CTV65gbeeP1RLPtq1eKr9ODeTs/8TroBVX1Ek8qmR4hyfp75pAmWokHuBfIJbH3vJEtb10tugzbUGbcQwUyLSMFJsYUTPaV85m03hdPQzt8ePDebJb6am9pjLhnCCXYi5PY9Tn2fEFdxF1e53DFEnJ8QCB5FOvn8/LWhFpV1TIZzMdL/zE9WoAlu0tNrQtYaUzNUJ7MKF4cTBucbM0e9sCVjuv/BEfXsUAXjgkmU09FaMK6M=
