dist: trusty
env:
  global:
  - TFBIN_DIR=$HOME/tfbin
  - TERRAFORM_VERSION=0.11.12
install:
- "./scripts/download_terraform.sh $TERRAFORM_VERSION"
script:
- "~/tfbin/terraform fmt -write=false -diff=true -check"
notifications:
  email: false
  slack:
    secure: pRfUCsk9SEVAqdVBs6faM7YyW8Qfbe/2tSxA9tIBgvHzt3scJ+jJmsnUQQN9RjlnUlKzBcpn94iFQu2OHdhxm4Ur6c9oRimzAaWBT8il0eTUILgcMOmIRD+LNZdPz9cySmDmIIq1vgkBtNhxNqEhwvWjWD8+R9XQxuJVvPbtJjl1xS3tK4n3xyMvmMq8N43ICv8gmLB9tJH09IuH1tETh7e2045VNIVwuI9XOPuSJk5mVwfegubap30LK193hjalB8XITg7aoFu38mqm0BfH1uWF5gM4vZe4ZLaqDxArLr1pt2y5wdT8QJ1J/K/PjbkKoP4d5l2vBzBRbqWtpPYGyhWIGfGpV98jyQCWJU0I1QRu1HQBN9ohg22aOmyRoXWDK3Ozn2U7bZGcnIHU88gPt+VY5yXtXIH5joHNz1jzxwyCz2ttjGCEUUQ3cRQrVaGI+YxqbIg8q8GI9b+sUZlvcXmVFcwCklQ+P3+4qa3o14Mojete1HQKATuE4pRDAL/saYYjTsyMHttFo9kmY6+qAHIjUOz8WylFYMbr98JsvtbYR2DskiMgADF69trJ6e2UgoRYv0XTJR9GoVcLkwUv7L+3yQi9Go0txHKm5bSe2bN5/ePleuJGq8Kz7Sa0EL7MQ59MbG9NrFqYhkHMG/6aQW1yImLTgF6b4CWZPrLtKTc=
